### ISSUE TITLE
Does not work revival button + funny animation respawn

### ISSUE THREAD

**Issue by f3f5-dev** [PaperMC/Folia#140] opened 2023-08-07 01:41 UTC
### Expected behavior

just see screenshot 
![2023-08-06_22 53 25](https://github.com/PaperMC/Folia/assets/137526883/3a4f411c-6e35-4f8f-8ed6-d543e6a94689)
![image](https://github.com/PaperMC/Folia/assets/137526883/5af8fdea-39c3-4a07-ac1a-5e574eec4f58)
![de](https://github.com/PaperMC/Folia/assets/137526883/b992ff8e-e454-4e2c-94fd-a60c640da557)

### Observed/Actual behavior

not my client issues, i see many people's report on 2b2t and my test server

### Steps/models to reproduce

spam /kill or Play and sometimes die on folia server

### Plugin and Datapack List

nope

### Folia version

b2d7bdb0bb5c841b4ccd096c0181664664ce97b1

### Other

.

**Comment by f3f5-dev** [comment] 2023-08-07 01:42
tested with vanilla too

**Comment by electronicboy** [comment] 2023-08-07 01:43
Duplicate of #112

**Closed by electronicboy** 2023-08-07 01:43 UTC
Labels: type: bug, status: needs triage
