### ISSUE TITLE
1.20 crash

### ISSUE THREAD

**Issue by MineSunshineone** [PaperMC/Folia#91] opened 2023-06-11 01:53 UTC
### Expected behavior

no crash like folia-1.19.4

### Observed/Actual behavior

https://pastes.dev/GdgFr21jMO

### Steps/models to reproduce

just tp around

### Plugin and Datapack List

> plugins
[09:50:18 INFO]: Server Plugins (19):
[09:50:18 INFO]: Bukkit Plugins:
[09:50:18 INFO]:  - AnCDK, ArmorStandEditor, Chunky, ColoredAnvils, CoreProtect, CreeperConfetti, DeathMessage, Essentials, EssentialsChat, GSit
[09:50:18 INFO]:  InvSeePlusPlus, Kaiivoid, LuckPerms, NoFlightInEnd, PistonMOTD, SkullPlugin, TAB, Vault, voicechat

### Folia version

> version
[09:50:52 INFO]: Checking version, please wait...
[09:50:53 INFO]: This server is running Folia version git-Folia-"9dcd6c2" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 9dcd6c2 on dev/1.20)
Error obtaining version information
Previous version: git-Folia-"3fde784" (MC: 1.20)

**Comment by MineSunshineone** [comment] 2023-06-11 03:06
another person in Discord
https://mclo.gs/hdl0hJc

**Comment by starmc63** [comment] 2023-06-12 08:57
Thread Region Scheduler Thread #4 failed main thread check: Cannot remove entity off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5477) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.world.ChunkEntitySlices.unload(ChunkEntitySlices.java:122) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:850) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:521) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:509) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:14:09] [Region Scheduler Thread #4/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #4 centered at chunk [549, 2164] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot remove entity off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5477) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.world.ChunkEntitySlices.unload(ChunkEntitySlices.java:122) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:850) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	at net.minecraft.server.level.ChunkTracker.processUnloads(ChunkTracker.java:521) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:509) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[kaiiju-1.20.jar:git-Kaiiju-"21321ab"]
	... 6 more
[16:14:09] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[16:14:09] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[16:14:09] [Region shutdown thread/INFO]: Stopping server

**Comment by paulpaul115** [comment] 2023-06-12 14:01
[09:43:15] [Region Scheduler Thread #1/ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot unload entity section off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entitySectionUnload(EntityLookup.java:702) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:859) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:521) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:509) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[09:43:16] [Region Scheduler Thread #1/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1 centered at chunk [0, 0] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1535) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot unload entity section off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entitySectionUnload(EntityLookup.java:702) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:859) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1306) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	at net.minecraft.server.level.ChunkTracker.processUnloads(ChunkTracker.java:521) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:509) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:455) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1678) ~[folia-1.20.jar:git-Folia-"9b2ffd0"]
	... 6 more
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[09:43:16] [Region shutdown thread/INFO]: Stopping server
[09:43:16] [Region shutdown thread/INFO]: [motdgg] Disabling motdgg v1.3.4
[09:43:16] [Region shutdown thread/INFO]: [BlueMap] Disabling BlueMap v3.14
[09:43:16] [Region shutdown thread/INFO]: [BlueMap] Stopping...
[09:43:16] [Region shutdown thread/INFO]: [BlueMap] Saved and stopped!
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Halting chunk systems
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Halted chunk systems
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world'
[09:43:16] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 18 block chunks, 99 entity chunks, 1 poi chunks in world 'world' in 0.09s
[09:43:16] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [-22, 186] in world 'world'
[09:43:18] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 1226 block chunks, 1226 entity chunks, 0 poi chunks in world 'world' in 1.77s
[09:43:18] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_nether'
[09:43:18] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 158 block chunks, 90 entity chunks, 0 poi chunks in world 'world_nether' in 0.20s
[09:43:18] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving chunks around region around chunk [0, 0] in world 'world_the_end'
[09:43:18] [Region shutdown thread/INFO]: [ChunkHolderManager] Saved 1 block chunks, 40 entity chunks, 0 poi chunks in world 'world_the_end' in 0.01s
[09:43:18] [Region shutdown thread/INFO]: [RegionShutdownThread] Saving players
[09:43:18] [Region shutdown thread/INFO]: Flushing Chunk IO
[09:43:18] [Region shutdown thread/INFO]: Closing Thread Pool
[09:43:18] [Region shutdown thread/INFO]: Closing Server

**Comment by Spottedleaf** [comment] 2023-06-12 20:01
Fixed by https://github.com/PaperMC/Folia/commit/23b6f9e0efe76505d936146529f7db3478e78ad6

**Closed by Spottedleaf** 2023-06-12 20:01 UTC
Labels: type: bug, status: needs triage

**Comment by cgw2023** [comment] 2023-06-19 04:55
> ### Expected behavior
> no crash like folia-1.19.4
> 
> ### Observed/Actual behavior
> https://pastes.dev/GdgFr21jMO
> 
> ### Steps/models to reproduce
> just tp around
> 
> ### Plugin and Datapack List
> > plugins
> > [09:50:18 INFO]: Server Plugins (19):
> > [09:50:18 INFO]: Bukkit Plugins:
> > [09:50:18 INFO]:  - AnCDK, ArmorStandEditor, Chunky, ColoredAnvils, CoreProtect, CreeperConfetti, DeathMessage, Essentials, EssentialsChat, GSit
> > [09:50:18 INFO]:  InvSeePlusPlus, Kaiivoid, LuckPerms, NoFlightInEnd, PistonMOTD, SkullPlugin, TAB, Vault, voicechat
> 
> ### Folia version
> > version
> > [09:50:52 INFO]: Checking version, please wait...
> > [09:50:53 INFO]: This server is running Folia version git-Folia-"9dcd6c2" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: [9dcd6c2](https://github.com/PaperMC/Folia/commit/9dcd6c26433cbffe084315d0758127ec86f0966b) on dev/1.20)
> > Error obtaining version information
> > Previous version: git-Folia-"3fde784" (MC: 1.20)
> 
> ### Other
> _No response_

may i ask an off topic question?
where can get folia version of ANCDK plugin? thx

**Comment by electronicboy** [comment] 2023-06-19 09:45
Please don't post on random tickets with offtopic questions, use the discord for support related stuff
