### ISSUE TITLE
Crash server - net.minecraft.ReportedException: Ticking player

### ISSUE THREAD

**Issue by RitaSister** [PaperMC/Folia#268] opened 2024-08-07 11:50 UTC
### Stack trace

https://mclo.gs/gHcJ7Dx

### Plugin and Datapack List

> plugins
[14:50:19 INFO]: Server Plugins (45):
[14:50:19 INFO]: Paper Plugins:
[14:50:19 INFO]:  - CarbonChat, FancyNpcs, FoliaWorldLoader
[14:50:19 INFO]: Bukkit Plugins:
[14:50:19 INFO]:  - ArmorStandEditor, AutoWhitelistRemove, BreweryX, CoreProtect, CoreProtectTNT, Craftorithm, DeluxeMenus, emotecraft, Essentials, EssentialsSpawn
[14:50:19 INFO]:  GSit, HeadDatabase, InventoryRollbackPlus, InvisibleFrames, InvSeePlusPlus, JoinMessenger, LiteBans, LuckPerms, Maintenance, Mclogs
[14:50:19 INFO]:  MilkyPixelart, NewbieFilter, OreAnnouncer, PlaceholderAPI, PlasmoVoice, PlayerHeads, ProtocolLib, pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib
[14:50:19 INFO]:  pv-addon-sculk, pv-addon-spectator, spark, squaremap, squaremarker, TAB, TWSAdmin, TWSCheck, UltimateAutoRestart, Vault
[14:50:19 INFO]:  WorldEdit, WorldGuard

### Actions to reproduce (if known)

Player just joined on server and server will be crashed.

### Folia version

> ver
[14:50:42 INFO]: Checking version, please wait...
[14:50:42 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-02T00:14:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-177c892 (MC: 1.21)

**Comment by xymb-endcrystalme** [comment] 2024-08-10 13:09
https://github.com/PaperMC/Folia/issues/264 - duplicate

**Comment by RitaSister** [comment] 2024-08-15 12:13
this will be fixed in 1.21.1?

**Comment by RitaSister** [comment] 2024-08-17 15:00
> #264 - duplicate

I think this issues is not have full logs all errors. So I think mine issues is not duplicate

**Comment by electronicboy** [comment] 2024-08-17 15:05
Duplicate of #264

**Closed by electronicboy** 2024-08-17 15:05 UTC
Labels: status: needs triage
