### ISSUE TITLE
1.20 Crash - Scheduling chunk load off-main

### ISSUE THREAD

**Issue by darkbro100** [PaperMC/Folia#94] opened 2023-06-13 00:37 UTC
### Stack trace

```
paste your stack trace or a paste.gg link here!

https://paste.gg/p/anonymous/bf31d18df645442eb16cbcddc10b8450
```

### Plugin and Datapack List

No Plugins

### Actions to reproduce (if known)

Walking in/out of a nether portal in survival mode (creative mode works fine)

### Folia version

> ver
[20:35:29 INFO]: Checking version, please wait...
[20:35:29 INFO]: This server is running Folia version git-Folia-"23b6f9e" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 23b6f9e on dev/1.20)
Error obtaining version information
Previous version: git-Folia-"ca3b7ad" (MC: 1.19.4)

### Other

Not much else, that's about it. Haven't done much more extensive testing, but between 2 different server setups the same crash happens (one on a fresh world, the other on an established world from 1.19.4). Interestingly creative mode seems to work fine when traveling through nether portals, but survival it crashes every time

**Comment by MineSunshineone** [comment] 2023-06-13 01:10
https://pastes.dev/a5En20k1s0
could reproduce in latest ver  
[09:09:18 INFO]: Checking version, please wait...
[09:09:20 INFO]: This server is running Folia version git-Folia-"02c651d" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 02c651d on dev/1.20)
Error obtaining version information

**Comment by starmc63** [comment] 2023-06-13 01:16
[09:08:18] [Region Scheduler Thread #6/ERROR]: Thread Region Scheduler Thread #6 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
	at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1386) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getOnPosLegacy(Entity.java:1368) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getBlockStateOnLegacy(Entity.java:1938) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.onChangedBlock(LivingEntity.java:612) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.onChangedBlock(ServerPlayer.java:1902) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:466) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:802) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2974) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:797) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:391) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:625) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:480) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:08:18] [Region Scheduler Thread #6/WARN]: [io.papermc.paper.threadedregions.RegionizedWorldData] Failed to handle packet for /202.98.81.193:15224
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:883) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:391) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:625) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:480) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Scheduling chunk load off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
	at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1386) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getOnPosLegacy(Entity.java:1368) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getBlockStateOnLegacy(Entity.java:1938) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.onChangedBlock(LivingEntity.java:612) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.onChangedBlock(ServerPlayer.java:1902) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:466) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:802) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2974) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:797) ~[?:?]
	... 8 more
[09:08:18] [Region Scheduler Thread #6/INFO]: PeterWuGuo lost connection: Internal server error
[09:08:18] [Region Scheduler Thread #6/ERROR]: Thread Region Scheduler Thread #6 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
	at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1386) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getBlockPosBelowThatAffectsMyMovement(Entity.java:1372) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2837) ~[?:?]
	at net.minecraft.world.entity.player.Player.travel(Player.java:1659) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3417) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:568) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3015) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:797) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:681) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:663) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2146) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2125) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:838) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:08:18] [Region Scheduler Thread #6/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #10 centered at chunk [-260, 88] in world 'world' failed to tick:
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:883) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:681) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:663) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2146) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2125) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:838) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1530) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Scheduling chunk load off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
	at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1386) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.Entity.getBlockPosBelowThatAffectsMyMovement(Entity.java:1372) ~[folia-1.20.jar:git-Folia-"23b6f9e"]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2837) ~[?:?]
	at net.minecraft.world.entity.player.Player.travel(Player.java:1659) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3417) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:568) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3015) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:797) ~[?:?]
	... 11 more
[09:08:18] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s

**Comment by hkkongou** [comment] 2023-06-13 06:44
may i ask a off topic question?
how to compile 1.20 version , i followed the paper mc guide but after compile it only give me 1.19.4 version
I don't know how to switch to 1.20 in intellJ IDEA

**Comment by starmc63** [comment] 2023-06-13 06:50
not switch
delete the Folia file already exists which you clone.
then:
git clone -b dev/1.20 <git link>

**Comment by Spottedleaf** [comment] 2023-06-13 21:27
Fixed by https://github.com/PaperMC/Folia/commit/db2e6578f8cfb04ab339ca9219ebbf6629d2f091

**Closed by Spottedleaf** 2023-06-13 21:27 UTC
Labels: status: needs triage
