### ISSUE TITLE
1.20 Villager error

### ISSUE THREAD

**Issue by Yomamaeatstoes** [PaperMC/Folia#92] opened 2023-06-12 00:41 UTC
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://mclo.gs/r4bfTfs

### Plugin and Datapack List

- AutoPay, BetterBoard, BetterEconomy, BetterRTP, BisectHosting-Folia, ChatFilter, Chunky, ClansLite, CrownSteal, DeluxeMenus, DisableBreeding, DiscordSRV, ElytraSpeed, EpicHomes, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GlobalTrackedMaps, IllegalStack, LuckPerms
 NoCheatPlus, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlugManX, ProtocolLib, RedLimiterReloaded, ScoreboardChatShop, SilkySpawnersLITE, Spartan
 StormerAntiSpamReloaded, StormerTPAReloaded, StormerWarpsReloaded, TerragenBiomesMockRegistry, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldGuard

### Actions to reproduce (if known)

Go near a villager

### Folia version

This server is running Folia version git-Folia-"9b2ffd0" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 9b2ffd0 on dev/1.20)

**Comment by ocelotpotpie** [comment] 2023-06-12 01:19
Can you reproduce this without any plugins?

If you're encountering errors like this the first step is to eliminate plugins as a possible culprit. Remove plugins and reproduce the issue.

If you can't reproduce the issue: then start adding plugins until it happens - that plugin is probably the problem.

If you can reproduce the issue: post that newer error log.

**Comment by MineSunshineone** [comment] 2023-06-12 01:42
like issue #90 and #91 'comment paste

**Comment by jpenilla** [comment] 2023-06-12 20:03
Duplicate of #91

**Closed by jpenilla** 2023-06-12 20:03 UTC
Labels: status: needs triage
