### ISSUE TITLE
Players lose their backpacks when they go offline

### ISSUE THREAD

**Issue by buildin1** [PaperMC/Folia#144] opened 2023-08-10 16:40 UTC
### Expected behavior

Fix this issue as he affects the gaming experience a lot

### Observed/Actual behavior

When the player goes offline there is a certain probability that the backpack will be completely emptied, it is determined that it is not caused by the plugin, and I have observed that other servers using the folia core will also have the problem of players losing their backpacks after going offline and then going online

### Steps/models to reproduce

I've recently observed emptying his backpack just 30 minutes after going offline, but not everyone does

### Plugin and Datapack List

Paper Plugins:
[00:39:04 INFO]:  - HuskHomes
[00:39:04 INFO]: Bukkit Plugins:
[00:39:04 INFO]:  - BetterRTP, BlockLocker, CoreProtect, FastAsyncWorldEdit, FreedomChat, GSit, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteBans
[00:39:04 INFO]:  LuckPerms, Matrix, PlaceholderAPI, PlayerTitle, ProtocolLib, TAB, ViaBackwards, ViaVersion, voicechat

### Folia version

Build #213

**Comment by ocelotpotpie** [comment] 2023-08-10 16:42
Do you mean player inventory, or an actual backpack provided by a mod or plugin?

We also do not have a build #213, can you provide the output of /version for your server?

**Comment by buildin1** [comment] 2023-08-11 07:29
> 
Checking version, please wait...
[15:15:18 INFO]: This server is running Folia version git-Folia-"f6e91e9" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6e91e9)

The player's item list is missing. Recently, players often have their backpack items available before they go offline, but after a while, all the backpack items disappear. This happens randomly and not every player will appear. I did not add a plugin to modify backpack items, and I am using the latest Folia core

**Comment by ocelotpotpie** [comment] 2023-08-11 21:10
How are you viewing these items?

This sounds like a potential issue with your InvSee plugins.

**Comment by KujouMolean** [comment] 2023-08-17 13:35
This cannot be a problem with Folia, but rather with a popular plugin. I have been using Folia since June 6th and have hardly added any third-party plugins. During this period, over 5000 players have played the server and there has never been a problem of player data loss.

**Comment by Jannyboy11** [comment] 2023-08-29 21:42
InvSee++ author here, perhaps I can shed some light on this issue. InvSee++ is architected in such a way that it tries to re-use spectator inventories as much as possible. I think this is one of its greatest strength; two admin players can modify the contents of a target player's inventories and they see their updates instaniously because they are sharing the same inventory instance. Also when a target player joins the server again, their inventory content is updated to whatever open content spectators still have. 
So when OP claims that they didn't add a plugin which modifies players' inventories, they are not correct.

I do know that this design comes with some drawbacks when running on Folia, because the InventoryViews that InvSee++ uses contain two inventories that are each owned by different entity schedulers, there is the top inventory which is only safe to access from the target player's EntityScheduler, and the bottom inventory, which is only safe to access from the spectating player's EntityScheduler. The InventoryViews that are presented to the admin player should therefore not modify the target's inventory directly, but rather create sequences of (immutable) modification operations, which should then be scheduled to execute on the target's EntityScheduler. [I have yet to implement this feature](https://github.com/Jannyboy11/InvSee-plus-plus/issues/58), which is why InvSee++'s resource page on SpigotMC claims Folia support is still experimental, and the Hangar and Modrinth pages don't even advertise Folia support.
On the other hand, OP claims that players lose their backpacks when players go offline. InvSee++ does not modify the player inventories when players go offline, instead it modifies them when they come online again (to synchronise the spectator view back to the target player), so this is what causes the bug that OP is experiencing. I have done some work locally to mitigate this, but have not implemented a bulletproof solution for this yet because of the usual excuses you see from plugin developers, busy in real life, yada yada.
While for many people this response is likely not a satisfying one, I hope this clears some things up.

**Comment by Nacioszeczek** [comment] 2023-08-30 04:27
I've tried logging onto an old Folia server I had for testing and couldn't reproduce, so I'm going to attribute it to what @Jannyboy11 said and consider it a plugin issue and close this.

Thanks for the report anyhow and if you need further help feel free to visit our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums).
If you can still reproduce this issue without plugins, reply here and we will reopen it.

**Closed by Nacioszeczek** 2023-08-30 04:27 UTC
Labels: type: bug, resolution: invalid
