### ISSUE TITLE
raid_omen effect causes crash in some situations

### ISSUE THREAD

**Issue by andreypfau** [PaperMC/Folia#278] opened 2024-08-19 16:54 UTC
### Stack trace

https://paste.gg/p/anonymous/58cceef8a2d3449381d518592ed5a308

### Plugin and Datapack List

No plugins

### Actions to reproduce (if known)

Unknown

### Folia version

[16:45:06 INFO]: This server is running Folia version 1.21.1-DEV-dev/1.21.1@9203a7a (2024-08-19T16:38:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-053b04c (MC: 1.21.1)

### Other

Temp fix: `/gamerule disableRaids true`

**Comment by andreypfau** [comment] 2024-08-19 17:07
Similar issue with villager passes through a nether portal, same exception for Accessing poi chunk off-main:
https://discord.com/channels/289587909051416579/1090762444550451281/1274790523701428296

**Comment by Warriorrrr** [comment] 2024-08-19 19:57
The raid omen effect issue is a duplicate of #264, please create seperate issues for other issues

**Closed by Warriorrrr** 2024-08-19 19:57 UTC
Labels: status: needs triage
