### ISSUE TITLE
1.20 crash when generating chunks

### ISSUE THREAD

**Issue by LexiLeeRanson** [PaperMC/Folia#90] opened 2023-06-11 01:11 UTC
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[https://paste.gg/p/anonymous/a2f36906cb034da98d65e6a19067be58](https://paste.gg/p/anonymous/a2f36906cb034da98d65e6a19067be58)

### Plugin and Datapack List

none

### Actions to reproduce (if known)

Server crashes shortly after players load new chunks

### Folia version

```
11.06 01:06:46 [Server] INFO This server is running Folia version git-Folia-"9b2ffd0" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 9b2ffd0 on dev/1.20)
11.06 01:06:46 [Server] INFO Error obtaining version information
11.06 01:06:46 [Server] INFO Previous version: git-Folia-115 (MC: 1.19.4)
```

**Comment by jpenilla** [comment] 2023-06-11 02:16
The paste link is invalid

**Comment by LexiLeeRanson** [comment] 2023-06-11 12:00
My apologies, heres the correct one

[https://paste.gg/p/anonymous/e89229d00fd64b6c868de24e613427ed](https://paste.gg/p/anonymous/e89229d00fd64b6c868de24e613427ed)

**Comment by kugge** [comment] 2023-06-11 22:28
Can reproduce when a player unload a chunk.

**Comment by jpenilla** [comment] 2023-06-12 20:02
Duplicate of #91

**Closed** 2023-06-12 20:03 UTC
Labels: status: needs triage
