### ISSUE TITLE
A server crash caused by some teleport command like /tpa or /back

### ISSUE THREAD

**Issue by starmc63** [PaperMC/Folia#84] opened 2023-06-03 11:08 UTC
[19:33:36] [Region Scheduler Thread #4/INFO]: zyfdage issued server command: /back
[19:33:38] [Region Scheduler Thread #5/INFO]: JEPXWE issued server command: /tpa OkayPlanet39241
[19:33:48] [Region Scheduler Thread #4/INFO]: zyfdage issued server command: /back
[19:33:51] [Region Scheduler Thread #5/INFO]: JEPXWE issued server command: /tpa nanfeng_123
[19:33:53] [Region Scheduler Thread #4/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1675 centered at chunk [58, -202] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1698) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:489) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:860) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:598) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:739) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	... 6 more
[19:33:53] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[19:33:53] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[19:33:53] [Region shutdown thread/INFO]: Stopping server

**Comment by starmc63** [comment] 2023-06-03 11:14
I report this problem to the author who developed a plugin called HuskHomes which can use'/tpa or /back'
https://github.com/WiIIiam278/HuskHomes2/issues/424
He asked me to report this issue to you.

**Comment by starmc63** [comment] 2023-06-03 11:54
And it seems like a teleport warmup problem?

**Comment by kugge** [comment] 2023-06-03 11:57
Duplicate of https://github.com/PaperMC/Folia/issues/45

**Comment by starmc63** [comment] 2023-06-03 13:44
And when player enter the nether portal,   it occurs too.
[21:21:11] [Region Scheduler Thread #12/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #4909 centered at chunk [53, 28] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1698) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Already sent chunk [-8, -5] in world 'world' to player EntityPlayer['Sysyxxx'/1267876, uuid='17cd4eea-8c6e-455c-946d-2862a31af44d', l='ServerLevel[world]', x=-125.50, y=96.00, z=-100.75, cpos=[-8, -7], tl=3992, v=true](Sysyxxx at -125.5,96.0,-100.74827201381764)
	at net.minecraft.server.level.ChunkHolder.addPlayer(ChunkHolder.java:136) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.updateChunkTracking(ChunkTracker.java:735) ~[?:?]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:485) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:860) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:598) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:739) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
	... 6 more
[21:21:11] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[21:21:12] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[21:21:12] [Region shutdown thread/INFO]: Stopping server

**Comment by maglink** [comment] 2023-06-09 22:44
@William278 Paperlib.asyncTeleport or player.asyncTeleport ?

**Comment by WiIIiam278** [comment] 2023-06-09 22:55
PaperLib.

I should note, this worked last time I tested it (at least with my plugin?) :)

**Comment by Spottedleaf** [comment] 2023-06-10 07:43
Possibly related to https://github.com/PaperMC/Folia/issues/45, if this occurs on 1.20 I can re-open

**Closed by Spottedleaf** 2023-06-10 07:43 UTC
Labels: version: 1.19, status: needs triage

**Comment by MineSunshineone** [comment] 2023-06-10 09:16
1.20 may still occurs
https://pastes.dev/56xwCASwrq

**Comment by redstonerti** [comment] 2023-06-12 08:36
It does occur on 1.20. Happened to me too

**Comment by MineSunshineone** [comment] 2023-06-12 08:39
> It does occur on 1.20. Happened to me too

nop please look #91 #90 #92

**Comment by redstonerti** [comment] 2023-06-12 08:47
What do you mean nope? It literally happened to me and I was the one that gave you the paste for 91

**Comment by MineSunshineone** [comment] 2023-06-12 08:56
> What do you mean nope? It literally happened to me and I was the one that gave you the paste for 91

this issue was the different between #91

**Comment by redstonerti** [comment] 2023-06-12 09:03
Oh ok sorry. I thought it was the same because it also happened when I was teleporting
