### ISSUE TITLE
Region #147924 centered at chunk [2346, 1802] in world 'world' failed to tick

### ISSUE THREAD

**Issue by starmc63** [PaperMC/Folia#114] opened 2023-07-01 07:51 UTC
### Stack trace

https://paste.gg/p/anonymous/5d1ff27978c1412d818f2f21067f4ee6

### Plugin and Datapack List

[15:50:52 INFO]: Server Plugins (31):
[15:50:52 INFO]: Paper Plugins:
[15:50:52 INFO]:  - HuskHomes
[15:50:52 INFO]: Bukkit Plugins:
[15:50:52 INFO]:  - AmazingBot, Attollo, BBeeChecker, BetterRTP, BlockLocker, Chunky, CodFrame, CoreProtect, FastAsyncWorldEdit, FoliaFlow
[15:50:52 INFO]:  FreedomChat, GreenChunk, GSit, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, Kaiivoid, LuckPerms, MiniMOTD, P
anilla
[15:50:52 INFO]:  PlaceholderAPI, PlasmoVoice, TAB, Towny, TownyChat, TownyFlight, TownyMenus, Vault, ViaBackwards, ViaVersion

### Actions to reproduce (if known)

teleport to another world

### Folia version

[15:50:33 INFO]: Checking version, please wait...
[15:50:34 INFO]: This server is running Kaiiju version git-Kaiiju-"349ae3b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Gi
t: 349ae3b on ver/1.20.1)
You are running the latest version
Previous version: git-Kaiiju-"8c562b0" (MC: 1.20.1)

**Comment by ocelotpotpie** [comment] 2023-07-01 07:56
Closing this because it is a fork of Folia, not Folia.

If you can reproduce it on Folia please do so and create a new issue.

**Comment by Spottedleaf** [comment] 2023-07-01 19:19
Fixed by https://github.com/PaperMC/Folia/commit/eb2231736b208862fc79e29c78582b660b9fbf4d

**Closed** 2023-07-01 19:19 UTC
Labels: status: needs triage
