### ISSUE TITLE
Server locks at 75% cpu with no players

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Folia#78] opened 2023-05-15 21:32 UTC
### Stack trace

[22:07:24] [Region Scheduler Thread #0/INFO]: Bot36 left the game
[22:07:24] [Region Scheduler Thread #0/INFO]: Bot14 lost connection: Disconnected
[22:07:24] [Region Scheduler Thread #0/INFO]: Bot14 left the game
[22:07:24] [Region Scheduler Thread #0/INFO]: Bot4 lost connection: Disconnected
[22:07:24] [Region Scheduler Thread #0/INFO]: Bot4 left the game

5 minutes after clients disconnected and Folia on fire at 75% CPU

Started dump - "jmap  -dump:file=ff.bin 13096"
```
[22:16:31] [WindowsStreamPump/WARN]: Exception in thread "WindowsStreamPump" Exception in thread "Thread-7" java.lang.OutOfMemoryError: Java heap space
[22:16:32] [Thread-7/WARN]: java.lang.OutOfMemoryError: Java heap space
[22:16:32] [RegionFile I/O Thread #0/ERROR]: [ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread] Exception thrown from prioritized runnable task in thread 'RegionFile I/O Thread #0'
java.lang.OutOfMemoryError: Java heap space
[22:16:32] [Region Scheduler Thread #0/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #0"
java.lang.OutOfMemoryError: Java heap space
[22:16:32] [Tuinity Chunk System Worker #0/ERROR]: [ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool] Exception thrown from thread 'Tuinity Chunk System Worker #0' in queue 'ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedPoolExecutorImpl@317eab95'
java.lang.OutOfMemoryError: Java heap space
[22:16:33] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[22:16:33] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[22:16:33] [Region shutdown thread/INFO]: Stopping server
```

### Plugin and Datapack List

none related, previous Folia builds didn't generate this problem

### Actions to reproduce (if known)

Start server, connect several clients and wait for the server to spike.

Disconnect all clients, wait several minutes and generate memory dump

### Folia version

latest aka folia-1.19.4-36 (Git: 7595ff6)

### Other

Dump generated (zip file ~700MB)

https://meocloud.pt/link/54086052-3d21-45e0-aaec-c6af1fd410b4/foliaDump.zip/

**Comment by Spottedleaf** [comment] 2023-05-16 04:54
Your server does not have enough memory to keep up with whatever stress test you're running. 

I noticed some problems locally, but these are not caused by Folia but are fixed on latest master. If it doesn't resolve your issue, you need more memory or you need to tune things like view distance / simulation disstance to reduce chunk loading/unloading.

**Closed by Spottedleaf** 2023-05-16 04:54 UTC
Labels: status: needs triage

**Comment by ricsal1** [comment] 2023-05-16 18:47
> Your server does not have enough memory to keep up with whatever stress test you're running.
> 
> I noticed some problems locally, but these are not caused by Folia but are fixed on latest master. If it doesn't resolve your issue, you need more memory or you need to tune things like view distance / simulation disstance to reduce chunk loading/unloading.

I will not try to refute the lack of memory on it, did it to force this situation reported that I had seen before in a situation with more memory.
My doubt and reason to report, was that the server was without any clients connected for several minutes (more then 5) burning cpu (seemed like an uncontrolled state) without throwing out of memory.
It only thrown the exception when I tried to capture the state with the dump.
I leave this info for future reference, if ever needed.
Regards

**Comment by mani1232** [comment] 2023-05-16 19:23
![image](https://github.com/PaperMC/Folia/assets/70480001/6ecd65f8-ffa0-42f5-8a49-776cb4e23515)
