### ISSUE TITLE
Using rcon via mcrcon is resulting in an error in the console and it not running the command

### ISSUE THREAD

**Issue by bovinespongiformflu** [PaperMC/Folia#183] opened 2024-01-19 21:29 UTC
### Expected behavior

when executing the command ./mcrcon  tps, i expect to get CLI output of the tps report given by the ingame command or the server console command "tps"

### Observed/Actual behavior

the server console/log spits out the following error.
[18:33:38] [RCON Listener #1/INFO]: Thread RCON Client /192.168.0.100 started
[18:33:38] [Region Scheduler Thread #3/WARN]: Unexpected exception while parsing console command "tps"
java.lang.UnsupportedOperationException: Dispatching command for org.bukkit.craftbukkit.v1_20_R3.command.CraftRemoteConsoleCommandSender@d12711e
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1024) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:981) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at net.minecraft.server.dedicated.DedicatedServer.lambda$runCommand$4(DedicatedServer.java:791) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.runOneTask(RegionizedServer.java:162) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.drainTasks(RegionizedServer.java:152) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:147) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"4d78338"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:33:38] [RCON Client /192.168.0.100 #2/INFO]: Thread RCON Client /192.168.0.100 shutting down

no output is visible from mcrcon, and it returns

mcftp@mc2:~/mcrcon$ ./mcrcon tps
mcftp@mc2:~/mcrcon$ 

I should see the tps report here.

### Steps/models to reproduce

make the mcrcon binary and export the host and password.
configure folia to enable rcon and setup a password in server.properties
then run mcrcon and a command to run

### Plugin and Datapack List

ArmorStandEditor, BlueMap, Chunky, ChunkyBorder, CoreProtect, DiscordSRV, GSit, LuckPerms, SeeMore, TabList

### Folia version

[21:29:06] [Thread-982/INFO]: This server is running Folia version git-Folia-"4d78338" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4d78338 on dev/1.20.4)
Error obtaining version information
Previous version: git-Folia-"1e5e215" (MC: 1.20.2)

**Comment by Netherwhal** [comment] 2024-01-19 23:13
Duplicate of #170

**Closed** 2024-01-20 01:42 UTC
Labels: type: bug, resolution: duplicate
