### ISSUE TITLE
Server threw an error while ticking an axolotl

### ISSUE THREAD

**Issue by MiskaDaeve** [PaperMC/Folia#245] opened 2024-07-28 16:09 UTC
### Stack trace

```
[23:56:58 ERROR]: Entity threw exception at world:-5676.567540324623,-27.78994546376124,-574.1961417528591
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftAxolotl.getHandle(CraftAxolotl.java:22) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftAxolotl.getHandle(CraftAxolotl.java:7) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.world.entity.ai.behavior.BabyFollowAdult.lambda$create$1(BabyFollowAdult.java:46) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.declarative.BehaviorBuilder$1.trigger(BehaviorBuilder.java:42) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.world.entity.ai.behavior.OneShot.tryStart(OneShot.java:17) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.world.entity.ai.behavior.GateBehavior$RunningPolicy$1.apply(GateBehavior.java:132) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.GateBehavior.tryStart(GateBehavior.java:60) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:451) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:403) ~[?:?]
        at net.minecraft.world.entity.animal.axolotl.Axolotl.customServerAiStep(Axolotl.java:283) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:961) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3484) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:698) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:63) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:460) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1560) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1369) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:1011) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:620) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:989) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ec6b172
"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ec6b172"
]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

![QQ_1722182873899](https://github.com/user-attachments/assets/4d16ee60-b0d9-467c-a807-689392da5f54)

### Folia version

ec6b1729ec9c3449cb65918d7af1ccf464ab3692

**Comment by Spottedleaf** [comment] 2024-12-09 01:05
Duplicate of https://github.com/PaperMC/Folia/issues/203

**Closed by Spottedleaf** 2024-12-09 01:05 UTC
Labels: status: needs triage
