### ISSUE TITLE
Player can't enter the server and is stuck at the entrance

### ISSUE THREAD

**Issue by RitaSister** [PaperMC/Folia#201] opened 2024-02-20 19:36 UTC
### Expected behavior

A player will be able to enter after being added to the whitelist.

### Observed/Actual behavior

After a player entered the server and got a kick with the reason that he is not on the whitelist. If after being added to the whitelist or re-entry, the player can no longer enter the server and is stuck at the entrance until 'Joining world...'.

### Steps/models to reproduce

1. Enable whitelisting.
2. Try to enter the server and get kicked by the whitelist.
3. Repeat the attempt to enter the server without adding to the whitelist (this is not the main thing, because after one time does not let you into the server).
4. You will get eternal login and loading into the world, and in the logs will be only this: [16:33:02] [User Authenticator #20/INFO]: UUID of player SteVyyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181 and further data will not go.
5. Saves and removes this situation only a complete reboot of the server command /stop.

```
[16:32:29] [User Authenticator #20/INFO]: UUID of player SteVyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181
768 | [16:32:57] [Region Scheduler Thread #3/INFO]: RitaSister issued server command: /whitelist add ]SteVyyyy09
769 | [16:32:59] [Region Scheduler Thread #3/INFO]: RitaSister issued server command: /whitelist add SteVyyyy09
770 | [16:32:59] [Region Scheduler Thread #0/INFO]: SteVyyyy09 (/**.**.**.**:36756) lost connection: Disconnected
771 | [16:32:59] [Region Scheduler Thread #3/INFO]: [RitaSister: Added SteVyyyy09 to the whitelist]
772 | [16:33:02] [User Authenticator #20/INFO]: UUID of player SteVyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181
773 | [16:33:26] [Region Scheduler Thread #3/INFO]: RitaSister issued server command: /whitelist add SteVyyyy09
774 | [16:33:32] [Region Scheduler Thread #0/INFO]: SteVyyyy09 (/**.**.**.**:36136) lost connection: Disconnected
775 | [16:33:34] [User Authenticator #20/INFO]: UUID of player SteVyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181
776 | [16:34:04] [Region Scheduler Thread #0/INFO]: SteVyyyy09 (/**.**.**.**:51906) lost connection: Disconnected
777 | [16:34:07] [Region Scheduler Thread #3/INFO]: faurtor issued server command: /w Hox_Lira СРОЧНО СПРЯЧЬСЯ В ТЕЧЕНИИ 1 МИНУТЫ, РЕСТАРТ
778 | [16:34:13] [User Authenticator #20/INFO]: UUID of player SteVyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181
779 | [16:34:43] [Region Scheduler Thread #0/INFO]: SteVyyyy09 (/**.**.**.**:42230) lost connection: Disconnected
780 | [16:34:55] [User Authenticator #20/INFO]: UUID of player SteVyyyy09 is 651fb335-278f-4d33-aada-ffbc0e802181
```
full log: https://mclo.gs/wZAIWur

### Plugin and Datapack List

[22:30:45 INFO]: Server Plugins (33):
[22:30:45 INFO]: Bukkit Plugins:
[22:30:45 INFO]:  - ArmorStandEditor, Brewery, Chunky, CoreProtect, CoreProtectTNT, Essentials, EssentialsSpawn, GSit, HeadDatabase, LiteBans
[22:30:45 INFO]:  LuckPerms, Maintenance, Mclogs, NewbieFilter, OfflineManager, OreAnnouncer, PlaceholderAPI, PlasmoVoice, PlayerHeads, ProtocolLib
[22:30:45 INFO]:  pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-sculk, pv-addon-spectator, RayTraceAntiXray, SexPlugin, SimpleChatL, spark, squaremap
[22:30:45 INFO]:  TAB, UralChat, Vault

Datapack is unavailable

### Folia version

> version
[22:35:55 INFO]: Checking version, please wait...
[22:35:56 INFO]: This server is running Folia version git-Folia-"8939611" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8939611)
You are running the latest version
Previous version: git-Folia-"7bc26ec" (MC: 1.20.4)

### Other

While researching this problem, I found the reason that this problem is specifically in the kernel, when I changed to a previous version, I stopped getting this bug and the login became free as it should be. I had to spend a lot of time to find if not the source, then at least a hint to this problem.

**Comment by Netherwhal** [comment] 2024-02-20 20:38
If you are also experiencing this without whitelist (which I also had issues with independently), then its a duplicate of #200 - I also was able to mitigate by downgrading version (if that is what you mean by Kernel).

**Closed** 2024-02-21 00:31 UTC
Labels: type: bug, status: needs triage
