### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by starmc63** [PaperMC/Folia#70] opened 2023-05-04 12:45 UTC
### Stack trace

[20:13:02 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #25599 centered at chunk [6237, -5615] in world 'world' fail
ed to tick:
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1716) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Fol
ia-"47105ea"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.ja
r:git-Folia-"47105ea"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar
:git-Folia-"47105ea"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Already sent chunk [6260, -5622] in world 'world' to player EntityPlayer['not_LOSER'/3793434, uu
id='9a609d35-ca6a-3a53-be21-3dd6d8cb3767', l='ServerLevel[world]', x=100167.27, y=63.80, z=-89813.95, cpos=[6260, -5614], tl=2457554, v=true
](not_LOSER at 100167.26906950824,63.796735600668704,-89813.94716536891)
        at net.minecraft.server.level.ChunkHolder.addPlayer(ChunkHolder.java:136) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.updateChunkTracking(ChunkTracker.java:735) ~[?:?]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.sendChunk(RegionizedPlayerChunkLoader.java:485) ~
[folia-1.19.4.jar:git-Folia-"47105ea"]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:860
) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[folia-1.19.4.jar:git-Folia
-"47105ea"]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:598) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:739) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
        ... 6 more
[20:13:02 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[20:13:02 INFO]: [RegionShutdownThread] Scheduler halted

### Plugin and Datapack List

[20:43:36 INFO]: Server Plugins (32):
[20:43:36 INFO]: Bukkit Plugins:
[20:43:36 INFO]:  - ArmorStandEditor, BBeeChecker, BetterRTP, BlueMap, ChestShop, Chunky, CoreProtect, DeluxeMenus, EditableSigns, Essential
s
[20:43:36 INFO]:  EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FallingSnow, FastAsyncWorldEdit, FoliaFlow, FramedIma
ge, GSit, InvSeePlusPlus
[20:43:36 INFO]:  InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteSignIn, LuckPerms, PlaceholderAPI, PosCommands, SurvivalPlots, UniHologram,
 Vault, ViaBackwards
[20:43:36 INFO]:  ViaRewind, ViaVersion

### Folia version

build of latest folia(1.19.4)

### Other

The more players there are,the higher the probability of this problem occuring.

**Comment by kugge** [comment] 2023-05-04 13:21
duplicate of #45 ?

**Comment by starmc63** [comment] 2023-05-07 06:59
New Problem?
[14:30:50] [Region Scheduler Thread #0/INFO]: YouXin joined the game
[14:30:50] [Region Scheduler Thread #0/INFO]: YouXin[/183.198.211.157:53873] logged in with entity id 4576323 at ([world]-978.0245502049388, 71.0, 2809.1456375847897)
[14:30:50] [Folia Async Scheduler Thread #5169/WARN]: [EssentialsGeoIP] 无法获取YouXin的GeoIP数据。请确认你的许可证密钥和配置是正确的。
[14:30:54] [Region Scheduler Thread #1/ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1123) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1110) ~[?:?]
	at net.minecraft.world.entity.raid.Raid.tick(Raid.java:410) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.raid.Raids.tick(Raids.java:75) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:735) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:30:54] [Region Scheduler Thread #1/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #44753 centered at chunk [5764, 5445] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1716) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot add effects to entities asynchronously
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1123) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1110) ~[?:?]
	at net.minecraft.world.entity.raid.Raid.tick(Raid.java:410) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.raid.Raids.tick(Raids.java:75) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:735) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	... 6 more
[14:30:54] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[14:30:54] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[14:30:54] [Region shutdown thread/INFO]: Stopping server
[14:30:54] [Region shutdown thread/INFO]: [ArmorStandEditor] Disabling ArmorStandEditor v1.19.4-42
[14:30:54] [Region shutdown thread/ERROR]: Error occurred (in the plugin loader) while disabling ArmorStandEditor v1.19.4-42 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.World.getCurrentWorldData()" is null
	at net.minecraft.world.level.Level.getBlockState(Level.java:818) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getNMS(CraftBlock.java:89) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:237) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getState(CraftBlock.java:352) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:253) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftInventory.getHolder(CraftInventory.java:548) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onDisable(ArmorStandEditorPlugin.java:344) ~[armorstandeditor-1.19.4-42.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:562) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1021) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:810) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.RegionShutdownThread.run(RegionShutdownThread.java:136) ~[folia-1.19.4.jar:git-Folia-"47105ea"]

**Comment by kugge** [comment] 2023-05-07 12:16
> New Problem? [14:30:50] [Region Scheduler Thread #0/INFO]: YouXin joined the game [14:30:50] [Region Scheduler Thread #0/INFO]: YouXin[/183.198.211.157:53873] logged in with entity id 4576323 at ([world]-978.0245502049388, 71.0, 2809.1456375847897) [14:30:50] [Folia Async Scheduler Thread #5169/WARN]: [EssentialsGeoIP] 无法获取YouXin的GeoIP数据。请确认你的许可证密钥和配置是正确的。 [14:30:54] [Region Scheduler Thread #1/ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously java.lang.Throwable: null at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1123) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1110) ~[?:?] at net.minecraft.world.entity.raid.Raid.tick(Raid.java:410) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.world.entity.raid.Raids.tick(Raids.java:75) ~[?:?] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:735) ~[?:?] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at java.lang.Thread.run(Thread.java:833) ~[?:?] [14:30:54] [Region Scheduler Thread #1/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #44753 centered at chunk [5764, 5445] in world 'world' failed to tick: net.minecraft.ReportedException: Exception ticking world at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1716) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.lang.IllegalStateException: Cannot add effects to entities asynchronously at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1123) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?] at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1110) ~[?:?] at net.minecraft.world.entity.raid.Raid.tick(Raid.java:410) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.world.entity.raid.Raids.tick(Raids.java:75) ~[?:?] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:735) ~[?:?] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"47105ea"] ... 6 more [14:30:54] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s [14:30:54] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted [14:30:54] [Region shutdown thread/INFO]: Stopping server [14:30:54] [Region shutdown thread/INFO]: [ArmorStandEditor] Disabling ArmorStandEditor v1.19.4-42 [14:30:54] [Region shutdown thread/ERROR]: Error occurred (in the plugin loader) while disabling ArmorStandEditor v1.19.4-42 (Is it up to date?) java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.World.getCurrentWorldData()" is null at net.minecraft.world.level.Level.getBlockState(Level.java:818) ~[?:?] at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getNMS(CraftBlock.java:89) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:237) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getState(CraftBlock.java:352) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:260) ~[?:?] at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:253) ~[?:?] at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftInventory.getHolder(CraftInventory.java:548) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin.onDisable(ArmorStandEditorPlugin.java:344) ~[armorstandeditor-1.19.4-42.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:562) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1021) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:810) ~[folia-1.19.4.jar:git-Folia-"47105ea"] at io.papermc.paper.threadedregions.RegionShutdownThread.run(RegionShutdownThread.java:136) ~[folia-1.19.4.jar:git-Folia-"47105ea"]

Already reported here: https://github.com/PaperMC/Folia/issues/65

**Comment by starmc63** [comment] 2023-05-11 12:41
[19:03:22] [Region Scheduler Thread #3/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #74 centered at chunk [-305, -3084] in world 'world' failed to tick:
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:882) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:666) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:648) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2138) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2117) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:834) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1537) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Accessing poi chunk off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.d(PoiManager.java:281) ~[?:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.exists(PoiManager.java:199) ~[?:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.existsAtPosition(PoiManager.java:82) ~[?:?]
	at net.minecraft.world.item.CompassItem.inventoryTick(CompassItem.java:80) ~[?:?]
	at net.minecraft.world.item.ItemStack.inventoryTick(ItemStack.java:768) ~[folia-1.19.4.jar:git-Folia-"47105ea"]
	at net.minecraft.world.entity.player.Inventory.tick(Inventory.java:328) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:565) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2978) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:275) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:796) ~[?:?]
	... 11 more

**Comment by Spottedleaf** [comment] 2023-05-13 23:56
This is an issue with the loadstone code, which I will fix. But you need to open different issues for different issues, as this thread contains way too many other issues, and they are duplicates.

**Closed by Spottedleaf** 2023-05-13 23:56 UTC
Labels: resolution: duplicate, version: 1.19
